templates_url/rel_url/app/urls.py
from app import views
from django.urls import include, path

# TEMPLATE TAGGING
app_name = 'app'

urlpatterns = [
    path('rel_url_templates/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('test/',views.test,name='test')
]

templates_url/rel_url/rel_url/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path("",views.index,name='index'),
    path('admin/', admin.site.urls),
    path('app/',include('app.urls'))
]

templates_url/rel_url/app/models.py
from django.db import models

templates_url/rel_url/app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    my_dict = {'text':'hello world','number':100}
    return render(request,'app/index.html',my_dict)

def other(request):
    return render(request,'app/other.html')

def relative(request):
    return render(request,'app/rel_url_templates.html')

def test(request):
    return render(request,'app/test.html')

templates_url/rel_url/templates/app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"><a href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'app:other'  %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_blocks %}
      <!-- Anything outside is inherited-->
      {% endblock %}

    </div>

  </body>
</html>

templates_url/rel_url/templates/app/index.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
{% load my_extras %}
    {% block body_blocks %}
    <h1>Welcome to Index.html!</h1>
    <h2>Using template inheritance</h2>
    <h1>{{text|upper}}</h1>
    <h1>{{text|cutter:'world'}}</h1>
    <h1>{{number|add:'99'}}</h1>
    {% endblock %}

templates_url/rel_url/templates/app/other.html
<!DOCTYPE html>
    {% extends "app/base.html" %}
    <h3>I am trying to opening your ass!</h3>
    {% block body_blocks %}
    <h1>Welcome to Other.html!</h1>
    <h2>Example of templated inheritance</h2>
    {% endblock %}

templates_url/rel_url/templates/app/rel_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Url</title>
  </head>
  <body>
    <h1>Welcome to URL.html!</h1>
    <a href="{% url 'app:other'  %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN</a>
    <a href="{% url 'index' %}">INDEX</a>
  </body>
</html>

templates_url/rel_url/templates/app/test.html
<!DOCTYPE html>
{% extends 'app/other.html' %}
    {% block body_blocks %}
    <h1>Welcome to test.html!</h1>
    <h2>Using template inheritance</h2>
    {% endblock %}